### ISSUE TITLE
Question: Elem.button - onClick?

### ISSUE THREAD

**Issue by JanBizub** [falcoframework/Falco#62]
Hello,

how do I assign function to button's onClick in Falco?

I am attempting something like: let button = Elem.button [ Attr.onClick (fun _ -> xxxx) ] [  ]

but it does not exist. I was looking into Falco source code for something like onClick but I have not found anything.

**Comment by JanBizub** [comment]
Hello Pim, thank you for reply. I was aware that lambda wont work it was just for illustration. It is reasonable. If I wanted javascript onClick then I add an id to the element using Attr.id reference .js file and assign onClick event there. What I was originally after was a button that redirects user, but I used Elem.a masked by bootstrap as button with href. I like Falco very much so far thank you for creating it. :)

**Comment by pimbrouwers** [comment]
Appreciate that! Glad you enjoy it! Tell your friends!
